/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamsRouteImport } from './routes/streams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsIdRouteImport } from './routes/streams.$id'

const StreamsRoute = StreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIdRoute = StreamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StreamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$id': typeof StreamsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$id': typeof StreamsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$id': typeof StreamsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/streams' | '/streams/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/streams' | '/streams/$id'
  id: '__root__' | '/' | '/streams' | '/streams/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamsRoute: typeof StreamsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$id': {
      id: '/streams/$id'
      path: '/$id'
      fullPath: '/streams/$id'
      preLoaderRoute: typeof StreamsIdRouteImport
      parentRoute: typeof StreamsRoute
    }
  }
}

interface StreamsRouteChildren {
  StreamsIdRoute: typeof StreamsIdRoute
}

const StreamsRouteChildren: StreamsRouteChildren = {
  StreamsIdRoute: StreamsIdRoute,
}

const StreamsRouteWithChildren =
  StreamsRoute._addFileChildren(StreamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamsRoute: StreamsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
